### ISSUE TITLE
Not async

### ISSUE THREAD

**Issue by MastaBaba** [10up/Async-Transients#5]
I've implemented this, but a new transient is not generated asynchronously, nor is the old transient returned when it has expired.

I've got a function that's supposed to return results, like so:

```
	$transientKey = "pis".$_POST["language"].$_POST["month"].$_POST["year"];

	$checkinNice = \TenUp\AsyncTransients\get_async_transient( $transientKey, 'get_month', array( $_POST["language"], $_POST["month"], $_POST["year"] ) );

	if(!$checkinNice) {
		$results = array();
	}
	else {
		$results = $checkinNice;
	}
```

Then, the 'get_month' function is like so:

```
function get_month($language, $month, $year) {
	global $wpdb;

	//Program items
	$date_start = date('Y-m-d H:i:s', mktime(0,0,0,$_POST["month"] - 1,1,$_POST["year"]));
	$date_end = date('Y-m-d H:i:s', -1 + mktime(0,0,0,$_POST["month"] + 2,1,$_POST["year"]));
	
	$args = array(...);

	$my_result = get_posts($args);

	\TenUp\AsyncTransients\set_async_transient( "pis".$language.$month.$year, $my_result, DAY_IN_SECONDS );	
}
```

This works, but when the transient has expired, the code takes as long to return results as without using async.

**Comment by cmmarslender** [comment]
Are you using an implementation of php that supports `fastcgi_finish_request` (such as nginx + php-fpm) ?

If you don't have support for `fastcgi_finish_request` it will regenerate the transients immediately.

**Comment by MastaBaba** [comment]
Ah. That's probably it. I would have to confirm, but I'm quite sure the server runs Apache.
